name: Update Hook documentation

on:
  workflow_dispatch:

jobs:
  build:
    name: Update Hook documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run package installs and builds
        run: |
          composer install
          composer update

      - name: Generate hooks documentation file
        run: vendor/bin/wp-documentor parse app --format=markdown --output=docs/hooks.md --prefix=eml_

      - name: Update file
        uses: tzkhan/pr-update-action@v2
        with:
            repo-token: "${{ secrets.GITHUB_TOKEN }}"
            base-branch-regex: '[a-z\d-_.\\/]+'
            head-branch-regex: 'foo-\d+'
            title-template: '[%headbranch%] '
            body-template: |
              Merging into '%basebranch%'
              [Link to %headbranch%](https://url/to/browse/ticket/%headbranch%)
            body-update-action: 'suffix'
            body-uppercase-base-match: false
